
 
#### Austria
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Austria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Austria',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Austria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Austria',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Austria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Austria',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Belgium
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Belgium',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Belgium',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Belgium',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Belgium',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Belgium',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Belgium',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Bulgaria
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Bulgaria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Bulgaria',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Bulgaria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Bulgaria',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Bulgaria',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Bulgaria',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Cyprus
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Cyprus',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Cyprus',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Cyprus',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Cyprus',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Cyprus',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Cyprus',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Czechia
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Czechia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Czechia',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Czechia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Czechia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Czechia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Czechia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Denmark
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Denmark',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Denmark',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Denmark',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Denmark',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Denmark',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Denmark',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Estonia
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Estonia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Estonia',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Estonia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Estonia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Estonia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Estonia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Finland
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Finland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Finland',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Finland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Finland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Finland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Finland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### France
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'France',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'France',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'France',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'France',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'France',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'France',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Germany
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Germany',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Germany',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Germany',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Germany',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Germany',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Germany',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Greece
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Greece',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Greece',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Greece',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Greece',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Greece',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Greece',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Hungary
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Hungary',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Hungary',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Hungary',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Hungary',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Hungary',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Hungary',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Ireland
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Ireland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ireland',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Ireland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ireland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Ireland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ireland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Israel
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Israel',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Israel',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Israel',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Israel',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Israel',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Israel',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Italy
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Italy',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Italy',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Italy',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Italy',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Italy',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Italy',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Lithuania
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Lithuania',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Lithuania',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Lithuania',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Lithuania',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Lithuania',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Lithuania',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Netherlands
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Netherlands',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Netherlands',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Netherlands',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Netherlands',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Netherlands',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Netherlands',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Norway
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Norway',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Norway',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Norway',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Norway',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Norway',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Norway',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Poland
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Poland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Poland',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Poland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Poland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Poland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Poland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Portugal
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Portugal',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Portugal',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Portugal',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Portugal',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Portugal',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Portugal',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Russia
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Russia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Russia',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Russia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Russia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Russia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Russia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Slovakia
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Slovakia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovakia',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Slovakia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovakia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Slovakia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovakia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Slovenia
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Slovenia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovenia',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Slovenia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovenia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Slovenia',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Slovenia',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Spain
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Spain',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Spain',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Spain',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Spain',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Spain',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Spain',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Sweden
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Sweden',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Sweden',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Sweden',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Sweden',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Sweden',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Sweden',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Switzerland
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Switzerland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Switzerland',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Switzerland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Switzerland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Switzerland',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Switzerland',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### Ukraine
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'Ukraine',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ukraine',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'Ukraine',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ukraine',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'Ukraine',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'Ukraine',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 
 
#### United Kingdom
```{r, echo=FALSE, warning=FALSE}
 
p_ess  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table %>% 
                             filter(source=='ESS'))$indicator),
  id_term = 'United Kingdom',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'United Kingdom',
  txt_subhead = 'ESS survey indicators',
  txt_caption = 'ESS 2002-2016',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_a  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max > pct_max_split))$indicator),
  id_term = 'United Kingdom',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'United Kingdom',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
p_wb_b  <- MakeIndicatorCountryPlot(
  ds = ds_ss_avg_ind_cntry %>% 
    filter(indicator %in% (indicator_table[idx_pct,] %>% 
                             filter(max <= pct_max_split))$indicator),
  id_term = 'United Kingdom',
  cntry_term = 'indicator',
  year_term = 'ess_year',
  txt_head = 'United Kingdom',
  txt_subhead = 'World Bank Development Indices & UNHCR',
  txt_caption = 'World Bank & UNHCR 2002-16',
  show_summary = FALSE,
  label_size_coef = lbl_coef,
  plevel = p_val)
 
MyPrintInteractive(p_ess$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_a$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
MyPrintInteractive(p_wb_b$ci, create_interactive_plot, hover_css = 'stroke-width:3px;') 
```
 

