---
title: "Worldback data"
output: html_notebook
---

Series Code	Topic	Indicator Name	Short definition
BX.TRF.PWKR.DT.GD.ZS	Economic Policy & Debt: Balance of payments: Current account: Transfers	Personal remittances, received (% of GDP)	
GC.DOD.TOTL.GD.ZS	Public Sector: Government finance: Deficit & financing	Central government debt, total (% of GDP)	
GC.TAX.TOTL.GD.ZS	Public Sector: Government finance: Revenue	Tax revenue (% of GDP)	
IT.NET.USER.ZS	Infrastructure: Communications	Individuals using the Internet (% of population)	
NY.GDP.MKTP.KD	Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators	GDP (constant 2010 US$)	
NY.GDP.MKTP.KD.ZG	Economic Policy & Debt: National accounts: Growth rates	GDP growth (annual %)	
NY.GDP.PCAP.KD	Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators	GDP per capita (constant 2010 US$)	
NY.GDP.PCAP.KD.ZG	Economic Policy & Debt: National accounts: Growth rates	GDP per capita growth (annual %)	
SE.XPD.TOTL.GD.ZS	Education: Inputs	Government expenditure on education, total (% of GDP)	
SH.XPD.GHED.GD.ZS	Health: Health systems	Domestic general government health expenditure (% of GDP)	
SL.TLF.CACT.ZS	Social Protection & Labor: Labor force structure	Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)	
SM.POP.TOTL.ZS	Social Protection & Labor: Migration	International migrant stock (% of population)	International migrant stock is the number of people born in a country other than that in which they live, including refugees.
SP.POP.TOTL	Health: Population: Structure	Population, total	
SP.RUR.TOTL.ZS	Environment: Density & urbanization	Rural population (% of total population)	
SP.URB.TOTL.IN.ZS	Environment: Density & urbanization	Urban population (% of total)	
SM.POP.REFG	Social Protection & Labor: Migration	Refugee population by country or territory of asylum

Refugees are people who are recognized as refugees under the 1951 Convention Relating to the Status of Refugees or its 1967 Protocol, the 1969 Organization of African Unity Convention Governing the Specific Aspects of Refugee Problems in Africa, people recognized as refugees in accordance with the UNHCR statute, people granted refugee-like humanitarian status, and people provided temporary protection. Asylum seekers -- people who have applied for asylum or refugee status and who have not yet received a decision or who are registered as asylum seekers--are excluded. Palestinian refugees are people (and their descendants) whose residence was Palestine between June 1946 and May 1948 and who lost their homes and means of livelihood as a result of the 1948 Arab-Israeli conflict. Country of asylum is the country where an asylum claim was filed and granted.



```{r}

library(dplyr)
library(ggplot2)
library(zoo)
library(ggrepel)
library(readxl)

WDIEXCEL <- read_excel("../Data/WDIEXCEL.xlsx")

inc_indicators <- c(
  'BX.TRF.PWKR.DT.GD.ZS', #	Economic Policy & Debt: Balance of payments: Current account: Transfers	Personal remittances, received (% of GDP)	
  'GC.TAX.TOTL.GD.ZS',    # Public Sector: Government finance: Revenue	Tax revenue (% of GDP)	
  'IT.NET.USER.ZS',       # Infrastructure: Communications	Individuals using the Internet (% of population)	
  'NY.GDP.MKTP.KD',       # Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators	GDP (constant 2010 US$)	
  'NY.GDP.MKTP.KD.ZG',    # Economic Policy & Debt: National accounts: Growth rates	GDP growth (annual %)	
  'NY.GDP.PCAP.KD',       # Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators	GDP per capita (constant 2010 US$)	
  'NY.GDP.PCAP.KD.ZG',    # Economic Policy & Debt: National accounts: Growth rates	GDP per capita growth (annual %)	
  'SE.XPD.TOTL.GD.ZS',    # Education: Inputs	Government expenditure on education, total (% of GDP)	
  'SH.XPD.GHED.GD.ZS',    # Health: Health systems	Domestic general government health expenditure (% of GDP)	
  'SL.TLF.CACT.ZS',       # Social Protection & Labor: Labor force structure	Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)	
  'SM.POP.TOTL.ZS',       # Social Protection & Labor: Migration	International migrant stock (% of population)	International migrant stock is the number of people born in a country other than that in which they live, including refugees.
  'SP.POP.TOTL',          # Health: Population: Structure	Population, total	
  'SP.RUR.TOTL.ZS',       # Environment: Density & urbanization	Rural population (% of total population)
  'SP.URB.TOTL.IN.ZS',    #	Environment: Density & urbanization	Urban population (% of total)	
  'SM.POP.REFG'           # Social Protection & Labor: Migration	Refugee population by country or territory of asylum
)

ds_wdi <- WDIEXCEL %>% 
  filter(`Indicator Code` %in% inc_indicators)

FixCountry <- function(ds, from, to) {
  idx <- which(ds$`Country Name` == from)
  ds$`Country Name`[idx] <- to
  return(ds)
}

ds_wdi <- FixCountry(ds_wdi, "Slovak Republic", "Slovakia")
ds_wdi <- FixCountry(ds_wdi, "Russian Federation", "Russia")
ds_wdi <- FixCountry(ds_wdi, "Czech Republic", "Czechia")

inc_countries <- unique(dataset$cntry_name)

ds_wdi <- ds_wdi %>% 
  filter(`Country Name` %in% inc_countries)

if (!identical(sort(unique(ds_wdi$`Country Name`)), sort(inc_countries))) stop("country names mismatch")


col_names <- colnames(ds_wdi)
ds_wdi <- ds_wdi[,col_names[c(1:4,44:62)]]

summary(ds_wdi)

# wide to narrow
new_df <- ds_wdi %>%
  gather(year, value, 5:23)
new_df$year <- as.numeric(new_df$year)

# fill missing
new_df <- new_df %>% 
  group_by(`Country Name`,`Indicator Code`) %>% 
  mutate(value = zoo::na.fill(value, "extend")) %>% 
  ungroup()

# calculate refugees by population
new_df2 <- new_df %>%
  select(-`Indicator Name`) %>%
  filter(`Indicator Code` %in% c('SM.POP.REFG','SP.POP.TOTL')) %>%
  spread(`Indicator Code`, value) %>%
  mutate(value = SM.POP.REFG/SP.POP.TOTL*100,
         `Indicator Code` = 'REFG.PCT',
         `Indicator Name` = 'Refugees pct of population') %>%
  select(-SM.POP.REFG, -SP.POP.TOTL)

new_df<- new_df %>%
  bind_rows(new_df2)



# Asylum seekers and refugees

ds_asyl <- read.csv("unhcr_popstats_export_time_series_all_data.csv", 
    skip = 3)

ds_asyl <- ds_asyl %>% 
  filter(Year >= min(new_df$year)) %>%
  mutate(`Country Name` = as.character(Country...territory.of.asylum.residence),
         year = Year,
         Value_num = as.numeric(trimws(Value))) %>%
  filter(!is.na(Value_num)) %>%
  group_by(`Country Name`, year) %>%
  summarise(value = sum(Value_num)) 

ds_asyl <- FixCountry(ds_asyl, "Russian Federation", "Russia")
ds_asyl <- FixCountry(ds_asyl, "Czech Rep.", "Czechia")

ds_asyl <- ds_asyl %>% 
  filter(`Country Name` %in% inc_countries)

if (!identical(sort(unique(ds_asyl$`Country Name`)), sort(inc_countries))) stop("country names mismatch")

code_from_country <- unique(new_df$`Country Code`)
names(code_from_country) <- unique(new_df$`Country Name`)

ds_asyl <- ds_asyl %>%
  mutate(`Country Code` = code_from_country[`Country Name`])

ds_asyl$`Indicator Name` <- 'Persons of concern'
ds_asyl$`Indicator Code` <- 'PERS.CONCERN'

new_df<- new_df %>%
  bind_rows(ds_asyl)

# pers of concern pct

new_df2 <- new_df %>%
  select(-`Indicator Name`) %>%
  filter(`Indicator Code` %in% c('PERS.CONCERN','SP.POP.TOTL')) %>%
  spread(`Indicator Code`, value) %>%
  mutate(value = PERS.CONCERN/SP.POP.TOTL*100,
         `Indicator Code` = 'PERS.CONCERN.PCT',
         `Indicator Name` = 'Persons of concern pct of population') %>%
  select(-PERS.CONCERN, -SP.POP.TOTL)

new_df<- new_df %>%
  bind_rows(new_df2)

# fill missing
new_df <- new_df %>% 
  group_by(`Country Name`,`Indicator Code`) %>% 
  mutate(value = zoo::na.fill(value, "extend")) %>% 
  ungroup()



for (indicator in unique(new_df$`Indicator Code`)){
  
  ds <- new_df %>% filter(`Indicator Code`==indicator)
  
  ds_labs0 <- ds %>% 
    filter(!is.na(value)) %>% 
    group_by(`Country Code`) %>% 
    arrange(desc(year)) %>%
    slice(1)
  ds_labs2 <- ds %>% 
    filter(!is.na(value)) %>% 
    group_by(`Country Code`) %>% 
    arrange(year) %>%
    slice(1)
  
  i <- 0
  ds_labs <- NULL
  for (cntry in unique(ds$`Country Code`)){
    i <- i + 1
    if ((i %% 2) == 0 ){
      ds_entry <- ds_labs0 %>% filter(`Country Code`==cntry)
    } else {
      ds_entry <- ds_labs2 %>% filter(`Country Code`==cntry)
    }
    ds_labs <- ds_labs %>%
      bind_rows(ds_entry)
  }
  
  ds_title <- ds$`Indicator Name`[1] 
  p <- ggplot() +
    labs(
      title = ds_title,
      subtitle = indicator,
      caption='Missing data points imputed with zoo') +
    geom_point(data=ds, aes(x=year, y=value, color=`Country Code`)) +
    geom_line(data=ds, aes(x=year, y=value, color=`Country Code`, group=`Country Code`)) +
    geom_text_repel(label=ds_labs$`Country Code`, size = 2, 
                     aes(x=ds_labs$year, y=ds_labs$value, color=ds_labs$`Country Code`))  + 
    theme(legend.position="none") +
    xlab("") + ylab("")
  
  print(p)
  
}

write.csv(new_df, file='wb.csv')

```

